logging:
  receivers:
    webapp-receiver:
      type: files
      include_paths:
        - /var/log/webapp-main/logfile.log
      record_log_file_path: true
  processors:
    webapp-processor:
      type: parse_json
      time_key: timestamp
      time_format: "%Y-%m-%d %H:%M:%S,%L"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.level
  service:
    pipelines:
      default_pipeline:
        receivers: [webapp-receiver]
        processors: [webapp-processor, move_severity]
